export const ACTION_DOWNLOAD = "ACTION_DOWNLOAD";
export const ACTION_DOWNLOAD_STOP = "ACTION_DOWNLOAD_STOP";

export const ACTION_VIDEO_ADD_CAMERA = "ACTION_VIDEO_ADD_CAMERA";
export const ACTION_VIDEO_UPDATE_CAMERA_STATE = "ACTION_VIDEO_UPDATE_CAMERA_STATE";
export const ACTION_VIDEO_UPDATE_CAMERA_TEMP = "ACTION_VIDEO_UPDATE_CAMERA_TEMP";
export const ACTION_VIDEO_CLEAR_CAMERAS = "ACTION_VIDEO_CLEAR_CAMERAS";

export const ACTION_VIDEO_SET_CAMERA_FILES = "ACTION_VIDEO_SET_CAMERA_FILES";
export const ACTION_VIDEO_CLEAR_CAMERA_FILES = "ACTION_VIDEO_CLEAR_CAMERA_FILES";
export const ACTION_VIDEO_DELETE_CAMERA_FILE = "ACTION_VIDEO_DELETE_CAMERA_FILE";

export const ACTION_SET_NETWORK = "ACTION_SET_NETWORK";