#ifndef COP_STATUS_CODE_H
#define COP_STATUS_CODE_H

enum StatusCode {
    
    STATUS_CODE_OK = 0,
    STATUS_CODE_NOK = -1,

    // JPEG encoder
    STATUS_CODE_JPEG_NOT_FOUND = -10,
    STATUS_CODE_JPEG_MEMORY_ERROR = -11,
    STATUS_CODE_JPEG_OPEN_ERROR = -12,

    // Player
    STATUS_CODE_PLAYER_CANT_OPEN_INPUT = -50,
    STATUS_CODE_PLAYER_CANT_FIND_STREAM_INFO = -51,

    STATUS_CODE_PLAYER_STREAM_INVALID_INDEX = -60,
    STATUS_CODE_PLAYER_STREAM_CANT_FIND_CODEC = -61,
    STATUS_CODE_PLAYER_STREAM_CANT_COPY_CODEC = -62,
    STATUS_CODE_PLAYER_STREAM_CANT_OPEN_AUDIO = -63,
    STATUS_CODE_PLAYER_STREAM_CANT_OPEN_CODEC = -64,
    STATUS_CODE_PLAYER_STREAM_MISSING_CODEC_INFO = -65
};

#endif /* COP_STATUS_CODE_H */
